// ツーリングスポット(全国)
// 注意: 座標は目安です(数百m〜数km ずれている可能性があります)。unverified: true は「位置・内容が未確認」の印です。
// vehicles: 対応する乗り物。今は全部 ["bike"]。車を足すときは "car" を加え、car: {...} ブロックを追加します。
// 二輪の通行や駐車の可否、有料道路の料金、通行止めの時期は、走る前に必ず公式情報を確認してください。
window.SPOTS = [
  { id: "s001", name: "美山かやぶきの里", area: "南丹市", lat: 35.2867, lng: 135.5350, vehicles: ["bike"], unverified: true,
    tags: ["景色", "山道", "ご飯"], bike: { note: "周辺に有料駐車場あり(要確認)" } },
  { id: "s002", name: "天橋立", area: "宮津市", lat: 35.5720, lng: 135.1940, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色", "観光"], bike: { note: "駐輪の可否・場所は要確認" } },
  { id: "s003", name: "伊根の舟屋", area: "伊根町", lat: 35.6700, lng: 135.2900, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色", "ご飯"], bike: { note: "道が狭い。徐行を" } },
  { id: "s004", name: "経ヶ岬", area: "京丹後市", lat: 35.7730, lng: 135.2210, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s005", name: "琴引浜", area: "京丹後市", lat: 35.6640, lng: 135.0380, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s006", name: "貴船神社", area: "京都市左京区", lat: 35.1600, lng: 135.7640, vehicles: ["bike"], unverified: true,
    tags: ["山道", "観光", "ご飯"], bike: { note: "道が狭く、週末は混雑" } },
  { id: "s007", name: "鞍馬寺", area: "京都市左京区", lat: 35.1180, lng: 135.7640, vehicles: ["bike"], unverified: true,
    tags: ["山道", "観光"], bike: { note: "" } },
  { id: "s008", name: "周山(京北)", area: "京都市右京区", lat: 35.1700, lng: 135.6400, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "国道162号沿い" } },
  { id: "s009", name: "笠置山", area: "笠置町", lat: 34.7570, lng: 136.0100, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "" } },
  { id: "s010", name: "宇治 平等院周辺", area: "宇治市", lat: 34.8890, lng: 135.8080, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s011", name: "比叡山ドライブウェイ周辺", area: "京都市左京区", lat: 35.0680, lng: 135.8360, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "通行料・二輪の可否は要確認" } },
  { id: "s012", name: "亀岡 保津川周辺", area: "亀岡市", lat: 35.0130, lng: 135.5670, vehicles: ["bike"], unverified: true,
    tags: ["景色", "ご飯"], bike: { note: "" } },
  { id: "s013", name: "宗谷岬", area: "稚内市", lat: 45.5220, lng: 141.9370, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "日本最北端の地" } },
  { id: "s014", name: "美瑛 パッチワークの路", area: "美瑛町", lat: 43.5900, lng: 142.4650, vehicles: ["bike"], unverified: true,
    tags: ["景色"], bike: { note: "丘陵地帯。農道や私有地への立ち入りに注意" } },
  { id: "s015", name: "ファーム富田", area: "中富良野町", lat: 43.4180, lng: 142.4310, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "ラベンダーの時期は混雑" } },
  { id: "s016", name: "摩周湖 第一展望台", area: "弟子屈町", lat: 43.5340, lng: 144.5360, vehicles: ["bike"], unverified: true,
    tags: ["景色"], bike: { note: "" } },
  { id: "s017", name: "阿寒湖", area: "釧路市", lat: 43.4300, lng: 144.1000, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s018", name: "野付半島", area: "別海町", lat: 43.5850, lng: 145.2700, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s019", name: "神威岬", area: "積丹町", lat: 43.3300, lng: 140.3560, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "強風の日は注意" } },
  { id: "s020", name: "洞爺湖", area: "洞爺湖町", lat: 42.5750, lng: 140.8290, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s021", name: "函館山", area: "函館市", lat: 41.7590, lng: 140.7050, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "夜景。山頂へのバイクの可否は要確認" } },
  { id: "s022", name: "大沼公園", area: "七飯町", lat: 41.9800, lng: 140.6800, vehicles: ["bike"], unverified: true,
    tags: ["景色"], bike: { note: "" } },
  { id: "s023", name: "龍飛崎", area: "外ヶ浜町", lat: 41.2530, lng: 140.3480, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s024", name: "十和田湖 休屋", area: "十和田市", lat: 40.4650, lng: 140.9040, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s025", name: "奥入瀬渓流", area: "十和田市", lat: 40.5000, lng: 140.9800, vehicles: ["bike"], unverified: true,
    tags: ["景色", "山道"], bike: { note: "" } },
  { id: "s026", name: "八幡平アスピーテライン", area: "八幡平市", lat: 39.9500, lng: 140.8500, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "開通期間は要確認" } },
  { id: "s027", name: "蔵王 御釜", area: "蔵王町", lat: 38.1440, lng: 140.4425, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "開通期間・天候による通行止めは要確認" } },
  { id: "s028", name: "松島", area: "松島町", lat: 38.3700, lng: 141.0600, vehicles: ["bike"], unverified: true,
    tags: ["海", "観光", "ご飯"], bike: { note: "" } },
  { id: "s029", name: "浄土ヶ浜", area: "宮古市", lat: 39.6470, lng: 141.9930, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s030", name: "磐梯吾妻スカイライン 浄土平", area: "福島市", lat: 37.7150, lng: 140.2470, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "開通期間は要確認" } },
  { id: "s031", name: "裏磐梯 五色沼", area: "北塩原村", lat: 37.6390, lng: 140.0770, vehicles: ["bike"], unverified: true,
    tags: ["景色"], bike: { note: "" } },
  { id: "s032", name: "大内宿", area: "下郷町", lat: 37.3350, lng: 139.8620, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s033", name: "奥日光 中禅寺湖", area: "日光市", lat: 36.7400, lng: 139.4680, vehicles: ["bike"], unverified: true,
    tags: ["景色", "山道"], bike: { note: "いろは坂は一方通行区間あり" } },
  { id: "s034", name: "戦場ヶ原", area: "日光市", lat: 36.7900, lng: 139.4300, vehicles: ["bike"], unverified: true,
    tags: ["景色"], bike: { note: "" } },
  { id: "s035", name: "榛名湖", area: "高崎市", lat: 36.4680, lng: 138.8500, vehicles: ["bike"], unverified: true,
    tags: ["景色", "山道"], bike: { note: "" } },
  { id: "s036", name: "草津白根 湯釜", area: "草津町", lat: 36.6180, lng: 138.5300, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "火山ガスによる規制に注意" } },
  { id: "s037", name: "碓氷峠 めがね橋", area: "安中市", lat: 36.3450, lng: 138.7350, vehicles: ["bike"], unverified: true,
    tags: ["山道", "観光"], bike: { note: "" } },
  { id: "s038", name: "三峯神社", area: "秩父市", lat: 35.9270, lng: 138.9330, vehicles: ["bike"], unverified: true,
    tags: ["山道", "観光"], bike: { note: "" } },
  { id: "s039", name: "奥多摩湖", area: "奥多摩町", lat: 35.7880, lng: 139.0490, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "" } },
  { id: "s040", name: "道志みち", area: "山梨県道志村", lat: 35.5990, lng: 139.0320, vehicles: ["bike"], unverified: true,
    tags: ["山道", "ご飯"], bike: { note: "取り締まりが多い区間あり。速度に注意" } },
  { id: "s041", name: "ヤビツ峠", area: "秦野市", lat: 35.4430, lng: 139.1550, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "季節・天候による通行止めあり" } },
  { id: "s042", name: "箱根 大観山", area: "箱根町", lat: 35.1970, lng: 139.0060, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "" } },
  { id: "s043", name: "鋸山", area: "富津市", lat: 35.1650, lng: 139.8320, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s044", name: "犬吠埼", area: "銚子市", lat: 35.7080, lng: 140.8690, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s045", name: "筑波山", area: "つくば市", lat: 36.2270, lng: 140.0980, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "" } },
  { id: "s046", name: "堂ヶ島", area: "西伊豆町", lat: 34.7590, lng: 138.7620, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s047", name: "城ヶ崎海岸", area: "伊東市", lat: 34.9080, lng: 139.1310, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s048", name: "山中湖", area: "山中湖村", lat: 35.4170, lng: 138.8700, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s049", name: "河口湖", area: "富士河口湖町", lat: 35.5170, lng: 138.7640, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s050", name: "ビーナスライン 車山高原", area: "茅野市", lat: 36.1000, lng: 138.1880, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "冬季通行止めあり" } },
  { id: "s051", name: "美ヶ原高原", area: "松本市", lat: 36.2360, lng: 138.1030, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "開通期間は要確認" } },
  { id: "s052", name: "諏訪湖", area: "諏訪市", lat: 36.0500, lng: 138.1100, vehicles: ["bike"], unverified: true,
    tags: ["景色", "ご飯"], bike: { note: "" } },
  { id: "s053", name: "奈良井宿", area: "塩尻市", lat: 35.9530, lng: 137.8130, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s054", name: "妻籠宿", area: "南木曽町", lat: 35.5790, lng: 137.5940, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s055", name: "飛騨高山 古い町並", area: "高山市", lat: 36.1400, lng: 137.2520, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s056", name: "白川郷", area: "白川村", lat: 36.2570, lng: 136.9060, vehicles: ["bike"], unverified: true,
    tags: ["観光", "景色"], bike: { note: "駐輪場は要確認" } },
  { id: "s057", name: "白米千枚田", area: "輪島市", lat: 37.3400, lng: 136.8980, vehicles: ["bike"], unverified: true,
    tags: ["景色", "海"], bike: { note: "" } },
  { id: "s058", name: "東尋坊", area: "坂井市", lat: 36.2360, lng: 136.1260, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s059", name: "三方五湖 レインボーライン", area: "若狭町", lat: 35.5750, lng: 135.8990, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "有料道路。二輪の料金・通行可否は要確認" } },
  { id: "s060", name: "御前崎", area: "御前崎市", lat: 34.5980, lng: 138.2270, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s061", name: "伊良湖岬", area: "田原市", lat: 34.5830, lng: 137.0180, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "フェリー利用の場合は運航情報を確認" } },
  { id: "s062", name: "伊勢神宮 内宮", area: "伊勢市", lat: 34.4550, lng: 136.7260, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s063", name: "潮岬", area: "串本町", lat: 33.4370, lng: 135.7580, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s064", name: "橋杭岩", area: "串本町", lat: 33.4830, lng: 135.7920, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s065", name: "那智の滝", area: "那智勝浦町", lat: 33.6680, lng: 135.8900, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s066", name: "熊野本宮大社", area: "田辺市", lat: 33.8400, lng: 135.7730, vehicles: ["bike"], unverified: true,
    tags: ["観光"], bike: { note: "" } },
  { id: "s067", name: "高野山", area: "高野町", lat: 34.2130, lng: 135.5850, vehicles: ["bike"], unverified: true,
    tags: ["山道", "観光"], bike: { note: "" } },
  { id: "s068", name: "姫路城", area: "姫路市", lat: 34.8390, lng: 134.6940, vehicles: ["bike"], unverified: true,
    tags: ["観光"], bike: { note: "" } },
  { id: "s069", name: "竹田城跡", area: "朝来市", lat: 35.3010, lng: 134.8300, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "山頂へは麓の駐車場から。二輪の駐車は要確認" } },
  { id: "s070", name: "大山", area: "大山町", lat: 35.3710, lng: 133.5400, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "" } },
  { id: "s071", name: "蒜山高原", area: "真庭市", lat: 35.3000, lng: 133.6200, vehicles: ["bike"], unverified: true,
    tags: ["景色", "ご飯"], bike: { note: "" } },
  { id: "s072", name: "鳥取砂丘", area: "鳥取市", lat: 35.5400, lng: 134.2270, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色", "観光"], bike: { note: "" } },
  { id: "s073", name: "出雲大社", area: "出雲市", lat: 35.4020, lng: 132.6850, vehicles: ["bike"], unverified: true,
    tags: ["観光"], bike: { note: "" } },
  { id: "s074", name: "宮島 厳島神社", area: "廿日市市", lat: 34.2960, lng: 132.3190, vehicles: ["bike"], unverified: true,
    tags: ["観光", "海"], bike: { note: "フェリー利用" } },
  { id: "s075", name: "岩国 錦帯橋", area: "岩国市", lat: 34.1670, lng: 132.1780, vehicles: ["bike"], unverified: true,
    tags: ["観光"], bike: { note: "" } },
  { id: "s076", name: "角島大橋", area: "下関市", lat: 34.3540, lng: 130.8780, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s077", name: "秋吉台 カルストロード", area: "美祢市", lat: 34.2380, lng: 131.3100, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "" } },
  { id: "s078", name: "しまなみ海道 来島海峡大橋", area: "今治市", lat: 34.1200, lng: 133.0300, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "原付・自転車専用の区間あり。通行区分は要確認" } },
  { id: "s079", name: "桂浜", area: "高知市", lat: 33.4970, lng: 133.5750, vehicles: ["bike"], unverified: true,
    tags: ["海", "観光"], bike: { note: "" } },
  { id: "s080", name: "室戸岬", area: "室戸市", lat: 33.2470, lng: 134.1800, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s081", name: "足摺岬", area: "土佐清水市", lat: 32.7200, lng: 133.0170, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s082", name: "四国カルスト 姫鶴平", area: "高知県津野町", lat: 33.4870, lng: 133.0230, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "冬季通行止めあり" } },
  { id: "s083", name: "祖谷 かずら橋", area: "三好市", lat: 33.8850, lng: 133.8090, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s084", name: "道後温泉", area: "松山市", lat: 33.8520, lng: 132.7860, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s085", name: "佐田岬灯台", area: "伊方町", lat: 33.3400, lng: 132.0100, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "細い道。すれ違いに注意" } },
  { id: "s086", name: "阿蘇 大観峰", area: "阿蘇市", lat: 33.0470, lng: 131.0700, vehicles: ["bike"], unverified: true,
    tags: ["景色", "山道"], bike: { note: "" } },
  { id: "s087", name: "やまなみハイウェイ 長者原", area: "九重町", lat: 33.1580, lng: 131.2400, vehicles: ["bike"], unverified: true,
    tags: ["山道", "景色"], bike: { note: "" } },
  { id: "s088", name: "高千穂峡", area: "高千穂町", lat: 32.7120, lng: 131.3010, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "" } },
  { id: "s089", name: "別府 海地獄", area: "別府市", lat: 33.3170, lng: 131.4730, vehicles: ["bike"], unverified: true,
    tags: ["観光"], bike: { note: "" } },
  { id: "s090", name: "湯布院", area: "由布市", lat: 33.2650, lng: 131.3570, vehicles: ["bike"], unverified: true,
    tags: ["観光", "ご飯"], bike: { note: "" } },
  { id: "s091", name: "桜島", area: "鹿児島市", lat: 31.5830, lng: 130.6570, vehicles: ["bike"], unverified: true,
    tags: ["景色", "観光"], bike: { note: "降灰時は路面が滑りやすい" } },
  { id: "s092", name: "開聞岳", area: "指宿市", lat: 31.1800, lng: 130.5290, vehicles: ["bike"], unverified: true,
    tags: ["景色", "山道"], bike: { note: "" } },
  { id: "s093", name: "佐多岬", area: "南大隅町", lat: 30.9950, lng: 130.6600, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s094", name: "雲仙地獄", area: "雲仙市", lat: 32.7420, lng: 130.2610, vehicles: ["bike"], unverified: true,
    tags: ["山道", "観光"], bike: { note: "" } },
  { id: "s095", name: "崎津集落", area: "天草市", lat: 32.5010, lng: 130.1220, vehicles: ["bike"], unverified: true,
    tags: ["海", "観光"], bike: { note: "" } },
  { id: "s096", name: "虹の松原", area: "唐津市", lat: 33.4550, lng: 130.0200, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s097", name: "古宇利大橋", area: "今帰仁村", lat: 26.6880, lng: 128.0230, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s098", name: "美ら海水族館", area: "本部町", lat: 26.6940, lng: 127.8780, vehicles: ["bike"], unverified: true,
    tags: ["観光"], bike: { note: "" } },
  { id: "s099", name: "辺戸岬", area: "国頭村", lat: 26.8700, lng: 128.2600, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } },
  { id: "s100", name: "残波岬", area: "読谷村", lat: 26.4400, lng: 127.7130, vehicles: ["bike"], unverified: true,
    tags: ["海", "景色"], bike: { note: "" } }
];
